const express=require('express');const crypto=require('node:crypto');
const router=express.Router();const intake=require('../services/twitchIntake');const chatsona=require('../services/chatsona');
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function formatInfo(body){return String(body).split(/\n\s*\n/).map(block=>{
 const lines=block.split('\n');
 return lines.map(line=>line.startsWith('### ')?'<h3>'+escape(line.slice(4))+'</h3>':line.startsWith('- ')?'<div>• '+escape(line.slice(2))+'</div>':'<div>'+escape(line.replace(/^\*(.*)\*$/,'$1'))+'</div>').join('');
}).map(block=>'<div>'+block+'</div>').join('<br>');}
function page(res,title,content,script=''){
 const nonce=crypto.randomBytes(18).toString('base64');
 res.set({'Cache-Control':'no-store','Referrer-Policy':'no-referrer','Content-Security-Policy':`default-src 'none'; script-src 'nonce-${nonce}'; style-src 'nonce-${nonce}'; connect-src 'self'; img-src blob:; frame-ancestors 'none'; base-uri 'none'; form-action 'none'`});
 res.type('html').send(`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} | StreamTools</title><style nonce="${nonce}">body{font:17px/1.6 system-ui;background:#101318;color:#f3f6fb;margin:0}main{max-width:850px;margin:4vh auto;padding:28px}section{background:#181d25;padding:22px;margin:20px 0;border:1px solid #333b4a;border-radius:10px}a{color:#8bbaff}button{background:#2f7df6;color:white;border:0;border-radius:6px;padding:12px 18px;cursor:pointer}button:disabled{opacity:.5}input{display:block;margin:20px 0;max-width:100%}.body{white-space:pre-wrap}img{max-height:220px;max-width:100%;background:#ddd}h1{line-height:1.2}</style><main><h1>${escape(title)}</h1>${content}</main>${script?`<script nonce="${nonce}">${script}</script>`:''}</html>`);
}
router.get('/commission-info',(req,res)=>{try{const info=intake.commissionInfo();page(res,'Commission information',`<p>Explore current options below, then join Discord to discuss a commission. This page does not submit a request.</p><a href="${info.invite}">Join the Discord server</a>`+info.sections.map(s=>`<section><h2>${escape(s.title)}</h2><div>${formatInfo(s.body)}</div></section>`).join(''));}catch{res.status(503).type('text').send('Commission information is temporarily unavailable.');}});
router.get('/chatsona/upload',(req,res)=>page(res,'Your Chatsona',`<p>Upload one static PNG up to 2 MB and 2048 x 2048 pixels. Staff will review it before it appears on stream. An approved image replaces your current Chatsona.</p><p id="status" role="status">Checking your private link…</p><section id="upload" hidden><label for="file">Choose your PNG</label><input id="file" type="file" accept="image/png"><img id="preview" alt="Selected Chatsona preview" hidden><p><button id="send" disabled>Submit for review</button></p></section><button id="refresh">Refresh review status</button><p>Keep this private link to check the decision for seven days. Never share it. A whisper notification will also be attempted.</p>`,String.raw`
const token=location.hash.slice(1);history.replaceState(null,'',location.pathname);let imageUrl;
const status=document.getElementById('status'),panel=document.getElementById('upload'),file=document.getElementById('file'),send=document.getElementById('send');
async function request(method='GET',body){const r=await fetch('/api/chatsona/upload',{method,headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'image/png'}:{})},body});const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed.');return data;}
async function refresh(){try{const data=await request();status.textContent=data.message;panel.hidden=!data.canUpload;}catch(e){status.textContent=e.message;panel.hidden=true;}}
file.onchange=()=>{const f=file.files[0];send.disabled=!f||f.size>2097152;if(f&&f.size>2097152)status.textContent='Choose a PNG no larger than 2 MB.';const preview=document.getElementById('preview');if(imageUrl)URL.revokeObjectURL(imageUrl);preview.hidden=!f;if(f){imageUrl=URL.createObjectURL(f);preview.src=imageUrl;}};
send.onclick=async()=>{send.disabled=true;try{const data=await request('POST',file.files[0]);status.textContent=data.message;panel.hidden=true;}catch(e){status.textContent=e.message;}finally{send.disabled=false;}};
document.getElementById('refresh').onclick=refresh;refresh();
`));
function authorize(req,res,next){res.set({'Cache-Control':'no-store','Referrer-Policy':'no-referrer'});try{req.chatsona=intake.authorized((req.headers.authorization||'').replace(/^Bearer /,''),req.method==='POST');next();}catch(e){res.status(403).json({error:e.message});}}
router.get('/api/chatsona/upload',authorize,(req,res)=>{const r=req.chatsona;const canUpload=r.status==='upload'&&r.uploadExpires>Date.now();const messages={upload:canUpload?'Verified Twitch viewer: '+r.twitchLogin+'. Choose your PNG.':'Upload link expired. Whisper !chatsona for a new link.',pending:'Your image is awaiting staff review.',approving:'Your image is being approved.',approved:'Approved! Your Chatsona is ready to use.',denied:'Your submission was denied. Contact staff on Discord or whisper !chatsona to submit a replacement.'};res.json({canUpload,status:r.status,message:messages[r.status]||'This request has expired.'});});
router.post('/api/chatsona/upload',authorize,(req,res,next)=>{if(req.get('Origin')!==new URL(process.env.CHATSONA_PUBLIC_URL).origin)return res.status(403).json({error:'Upload from the private Chatsona page.'});next();},express.raw({type:'image/png',limit:'2mb'}),async(req,res)=>{try{await chatsona.submitWeb(req.chatsona,req.body);res.json({message:'Your image was received and is awaiting staff review.'});}catch(e){res.status(400).json({error:e.code?'Upload could not be processed. Refresh status before retrying.':e.message});}});
router.use((err,req,res,next)=>{if(err.type==='entity.too.large')return res.status(413).json({error:'PNG files must be no larger than 2 MB.'});next(err);});
module.exports=router;
